name: "DBT CI/CD Pipeline"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allows manual execution

jobs:
  dbt-ci-cd:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install DBT & Snowflake Adapter
        run: |
          pip install dbt-core dbt-snowflake

      - name: Configure DBT Profiles
        run: |
          mkdir -p ~/.dbt
          echo "${{ secrets.DBT_PROFILES }}" > ~/.dbt/profiles.yml

      - name: Install DBT Dependencies
        run: dbt deps

      - name: Run DBT Tests (Production)
        run: dbt test --target prod  # Uses the production target

      - name: Run DBT Models (Production)
        run: dbt run --target prod --exclude tag:skip_ci  # Runs models except those tagged as skip_ci

      - name: Check DBT Model Performance
        run: |
          cat target/run_results.json | jq '.results[] | {model: .unique_id, time: .execution_time}'
